### ISSUE TITLE
Provide Binary releases

### ISSUE THREAD

**Issue by brpaz** [AndrewRadev/quickmd#11]
Hi.

Great tool ;)

It would be nice to provide a binary release, It took me some time to build everything on my machine, and had to install some missing dependencies, as well as having the rust toolchain (which I already had, but for other users might be complicated to setup).

It should be simple to do with GitHub actions. For example: https://alican.codes/rust-github-actions/

**Comment by AndrewRadev** [comment]
Thanks for the link -- I've used the example code in the article mostly as-is, and it seems to produce a binary :+1:. Here's the first release with one attached: https://github.com/AndrewRadev/quickmd/releases/tag/v0.4.1

I should write up instructions in the README, but could you try the executable as well, let me know if you see any issues? One problem is that I'm pretty sure it'll still require gtk and webkit2gtk to be installed on the system, and I'm not sure about version expectations -- I'm curious whether your setup will execute the binary successfully as well. In any case, it's a start.

**Comment by brpaz** [comment]
Cool. I tested the binary and seems to work fine.

**Comment by AndrewRadev** [comment]
Awesome, thanks. I've updated the README to note the downloadable release, so I'll close this issue for now. Let me know if you run into issues or have other suggestions about the build process.
