### ISSUE TITLE
File watching is broken with NeoVim

### ISSUE THREAD

**Issue by cheap-glitch** [AndrewRadev/quickmd#12]
The preview isn't updated when saving changes to the watched file in NeoVim.

Looking at the debug logs, it seems `quickmd` detects the file as being removed and recreated, instead of being modified:
```text
[DEBUG quickmd::background] Ignored watcher event: NoticeRemove("/home/florent/dev/devlint/README.md")
[DEBUG quickmd::background] Ignored watcher event: Create("/home/florent/dev/devlint/README.md")
[DEBUG quickmd::background] Ignored watcher event: NoticeRemove("/home/florent/dev/devlint/README.md")
[DEBUG quickmd::background] Ignored watcher event: Create("/home/florent/dev/devlint/README.md")
```

This doesn't happen with other editors (tested in Leafpad and nano).

I have some rudimentary knowledge of Rust, so if this is an easy fix I can try to take a stab at it. Otherwise, I'd still be happy with a quick keybinding to manually refresh the preview, e.g. `r` of `F11` :smile:

**Comment by AndrewRadev** [comment]
Hmm, that's odd, I thought this was actually implemented. I have a test that's supposed to remove a file and then recreate it. I wonder if there's a difference in event handling depending on operating systems.

Just for my information, could you try running `cargo test` locally and let me know if any of the tests fail? Other than that, though, I've also pushed a commit that I'm hoping should fix it -- try updating the main branch?

> Otherwise, I'd still be happy with a quick keybinding to manually refresh the preview, e.g. r of F11

This is also a good idea as a manual escape hatch. I'll keep it in mind while working on custom keybindings.

**Comment by cheap-glitch** [comment]
> I wonder if there's a difference in event handling depending on operating systems.

I'm on Arch Linux btw.

That said I've never had any problems with file watchers before, whether JS-basd (like `chokidar`) or Rust-based (`watchexec`). But in the end they probably rely on the same system APIs anyway.

> Other than that, though, I've also pushed a commit that I'm hoping should fix it -- try updating the main branch?

Yes it's fixed, thank you! I'm closing the issue then.

> Just for my information, could you try running cargo test locally and let me know if any of the tests fail?

No, they all pass. Fyi I also tried on the previous commit (7c1f2ee71d64f3b3a6461cff249fc8f5ba79043a) and they all pass too, so I don't think they would have caught this bug in the first place.

**Comment by AndrewRadev** [comment]
Hmm, well, I still have no explanation as to why it's happening, then. But I suppose if it works, it works. The only thing I'd be worried about is double-rendering, but I didn't really see anything like that for me, so it should be fine.
