### ISSUE TITLE
Support relative paths for embedded images

### ISSUE THREAD

**Issue by cheap-glitch** [AndrewRadev/quickmd#13]
GitHub lets you use relative links when referring to images (and any other files) in the repo, e.g.
```md
![Company logo](distribution/media/logo.png)
```

It would be nice if `quickmd` supported this. Ideally it would look for the file starting at the root of the current Git repo, but for a start using the directory of the current file would be good enough.

I can try opening a PR for this if it's not too hard to implement.

**Comment by AndrewRadev** [comment]
Currently, it's possible to render a file-relative image using `![Company logo](./distribution/media/logo.png)` -- that gets parsed right here: https://github.com/AndrewRadev/quickmd/blob/7c1f2ee71d64f3b3a6461cff249fc8f5ba79043a/src/markdown.rs#L55-L57

I'd be happy to implement rendering your example as well. In fact, I think I considered it, but I wasn't sure if it was a file path or a domain name. Now that I'm testing, though, it seems it only parses URLs if they start with `http://` or `https://`, so maybe it'd be quite simple to get this done by changing the `.starts_with?` with a check for not starting with `http://` or with `https://`. Or maybe even `.\w+://` for stuff like `ftp://` or `file://`. 

> Ideally it would look for the file starting at the root of the current Git repo,

According to this doc, I think repo-root-relative files start with `/`? https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#images

This would also be fine to implement, and pretty useful -- the code could check for a `.git` file or directory upwards, and if it exists, check if that file exists. But maybe both of these could be done separately.

> I can try opening a PR for this if it's not too hard to implement.

I think it should be relatively easy to use the [regex](https://crates.io/crates/regex) crate to check that the "url" in that code doesn't start with a protocol and `://`. There's also a test that would need to be tweaked and maybe extended: https://github.com/AndrewRadev/quickmd/blob/7c1f2ee71d64f3b3a6461cff249fc8f5ba79043a/tests/test_markdown.rs#L32-L50

If you don't have the time/energy or Rust experience, I can take care of it as well -- let me know :+1:.
